feat: update framework to .net 8.0
Dataport/terminfinder-backend pull request #9
Opened 2024-10-02 11:39 UTC by umoelli

- update framework to .net 8
- update libraries
- add new environment 'Terminfinder__dbmigrate' with the same function as the argument '--dbmigrate'
- modification of dockerfiles and docker compose, especially for postgres

2024-10-02 13:51 UTC, tjorbo requested changes
Hey @umoelli
Danke für deine Änderungen! 🍀 

Der Container für die Dev-DB ist eine gute Idee! Wir bräuchten nur noch das Script, was kopiert werden soll und dann ists echt komfortabel zu entwickeln. Danke!

2024-10-09 09:00 UTC, BGruenberg approved these changes

2024-10-15 06:09 UTC, BGruenberg approved these changes

2024-10-15 08:39 UTC, tjorbo requested changes
Hey @umoelli 
habe noch den User umgestellt, damit der Postgres Server nicht als Root läuft und das initdb script ausgeführt.

Bei mir startet die DB nun und kann Verbindungen annehmen.

2024-10-15 08:39 UTC, tjorbo commented on db/Dockerfile
> +COPY create_user.sql /docker-entrypoint-initdb.d
```suggestion
EXPOSE 5432

COPY create_user.sql /docker-entrypoint-initdb.d

USER "999:999"

RUN initdb
```

2024-10-24 07:07 UTC, merged